### ISSUE TITLE
runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by aditya520** [chriswalz/bit#2]
Tried installing using curl commands, installed successfully. 
While testing `bit` I got 
```exit status 1
runtime error: index out of range [1] with length 1
goroutine 1 [running]:
runtime/debug.Stack(0x6bf1c0, 0xc000182008, 0xc00008d760)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/chriswalz/bit/cmd.HandleExit()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.7/cmd/util.go:320 +0xc5
panic(0x636820, 0xc000180300)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/chriswalz/bit/cmd.AllGitSubCommands(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.7/cmd/util.go:350 +0x549
github.com/chriswalz/bit/cmd.AllBitAndGitSubCommands(0x7fa240, 0xc00010e040, 0x5, 0x8)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.7/cmd/util.go:377 +0x59
github.com/chriswalz/bit/cmd.glob..func3(0x7fa240, 0x82e7e8, 0x0, 0x0)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.7/cmd/rootShell.go:21 +0x65
github.com/spf13/cobra.(*Command).execute(0x7fa240, 0xc00018a010, 0x0, 0x0, 0x7fa240, 0xc00018a010)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x7fa240, 0x5def05, 0xc0001cc000, 0xc0001d4000)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/chriswalz/bit/cmd.Execute()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.7/cmd/rootShell.go:66 +0x31
main.bitcli(...)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.7/main.go:49
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.7/main.go:42 +0x171
```

**Comment by chriswalz** [comment]
What OS and Terminal are you using? It seems like the `git help -a` command that bit runs isn't returning anything. If you run `git help -a` does that work?

**Comment by aditya520** [comment]
I am using Ubuntu 18.04 LTS. 
`git help -a` gives me
```usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

available git commands in '/usr/lib/git-core'

  add                       cherry-pick               difftool--helper          imap-send                 merge-recursive           read-tree                 rev-parse                 tag
  add--interactive          clean                     fast-export               index-pack                merge-resolve             rebase                    revert                    unpack-file
  am                        clone                     fast-import               init                      merge-subtree             rebase--helper            rm                        unpack-objects
  annotate                  column                    fetch                     init-db                   merge-tree                receive-pack              send-pack                 update-index
  apply                     commit                    fetch-pack                instaweb                  mergetool                 reflog                    sh-i18n--envsubst         update-ref
  archive                   commit-tree               filter-branch             interpret-trailers        mktag                     remote                    shell                     update-server-info
  bisect                    config                    fmt-merge-msg             log                       mktree                    remote-ext                shortlog                  upload-archive
  bisect--helper            count-objects             for-each-ref              ls-files                  mv                        remote-fd                 show                      upload-pack
  blame                     credential                format-patch              ls-remote                 name-rev                  remote-ftp                show-branch               var
  branch                    credential-cache          fsck                      ls-tree                   notes                     remote-ftps               show-index                verify-commit
  bundle                    credential-cache--daemon  fsck-objects              mailinfo                  pack-objects              remote-http               show-ref                  verify-pack
  cat-file                  credential-store          gc                        mailsplit                 pack-redundant            remote-https              stage                     verify-tag
  check-attr                daemon                    get-tar-commit-id         merge                     pack-refs                 remote-testsvn            stash                     web--browse
  check-ignore              describe                  grep                      merge-base                patch-id                  repack                    status                    whatchanged
  check-mailmap             diff                      hash-object               merge-file                prune                     replace                   stripspace                worktree
  check-ref-format          diff-files                help                      merge-index               prune-packed              request-pull              submodule                 write-tree
  checkout                  diff-index                http-backend              merge-octopus             pull                      rerere                    submodule--helper
  checkout-index            diff-tree                 http-fetch                merge-one-file            push                      reset                     subtree
  cherry                    difftool                  http-push                 merge-ours                quiltimport               rev-list                  symbolic-ref

git commands available from elsewhere on your $PATH

  deborig

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
```

**Comment by chriswalz** [comment]
Thanks for letting me know. I've updated the code and tested it on an Ubuntu machine. It should work now
