### ISSUE TITLE
bitcomplete not working properly

### ISSUE THREAD

**Issue by faizalpribadi** [chriswalz/bit#3]
Hi @chriswalz,

after installing `bit` and `bitcomplete` too, bit completion not working properly ( panic goroutine ), any idea ? 

<img width="1792" alt="Screen Shot 2020-10-07 at 14 25 14" src="https://user-images.githubusercontent.com/1262414/95300287-2816a500-08a9-11eb-88d6-3394d56e47bd.png">

**Comment by reflog** [comment]
Similar problem here, doing 'bit TAB' prints:
```
➜ bit panic: COMP_POINT env should be integer, got: 

goroutine 1 [running]:
github.com/posener/complete/v2.Complete(0x661167, 0x3, 0x6d88a0, 0xc000286f00)
        /go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/complete.go:79 +0x57f
github.com/posener/complete/v2.(*Command).Complete(...)
        /go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/command.go:20
main.main()
        /go/pkg/mod/github.com/chriswalz/bit@v0.4.10/bitcomplete/complete.go:57 +0x75b

```

**Comment by mcarifio** [comment]
bit could be useful, so I hope I can get it working to understand it better. Not trying to pile on here.

I think I get the same error, but I get a different error message so I thought I'd add the additional message(s) in hopes they might help:

```bash

$ bitcomplete # should this be run at the command line?
goroutine 1 [running]:
github.com/chriswalz/bit/cmd.AllGitAliases(0x8, 0x4, 0x203000)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.10/cmd/util.go:344 +0x505
github.com/chriswalz/bit/cmd.AllBitAndGitSubCommands(0x8159a0, 0xc00000e3e0, 0x5f1a74, 0x66b0ba)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.10/cmd/util.go:365 +0x37
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.10/bitcomplete/complete.go:26 +0x72
 


(master) mcarifio@shuttle:/opt/bit/current/bin$p go version  # go version and go env
go version go1.15.2 linux/amd64
 
(master) mcarifio@shuttle:/opt/bit/current/bin$p go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mcarifio/.cache/go-build"
GOENV="/home/mcarifio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mcarifio/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mcarifio/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/6439"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/6439/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build776571046=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by chriswalz** [comment]
@mcarifio 

`COMP_INSTALL=1 bitcomplete` should only be run once during installation. After just use `bit`. 

There may be an issue with inconsistencies across OSs around how commands output information. 

Do you mind posting the output for this command 

`git config --get-regexp alias`

**Comment by chriswalz** [comment]
@reflog what OS are you on? It seems like when running `COMP_INSTALL=1 bitcomplete` it didn't accept the environment variable

@faizalpribadi same question for you.

Hopefully we'll get it sorted out soon

**Comment by mcarifio** [comment]
```bash
$ git config --get-regexp alias # don't use a lot of these
alias.revert checkout HEAD --
alias.unstage reset HEAD --
alias.last log -1 HEAD
alias.co checkout
alias.cob checkout -b
alias.switch checkout
alias.sw checkout
alias.sg log --graph --abbrev-commit --pretty=oneline
alias.root rev-parse --show-toplevel
alias.s status
alias.stage add
alias.staged status
alias.hist log --pretty=format:"%h %ad | %s%d [%an]" --graph
alias.h hist
alias.vis !qgit
alias.replay rebase
alias.path !echo $PATH | tr ':' '
'
alias.br branch
alias.make !make -C ~/.config/git/git.config.d

$ lsb_release -a  # just upgraded 19.10 -> 20.04; it was a bumpy ride...
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

$ uname -a  # just in case
Linux shuttle 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Note that consistent with recent versions of Ubuntu, I installed `go` using [`snap`](https://snapcraft.io/docs). As long as I use `go env`, for various locations, all is well. In particular `go env GOPATH` is typically `$HOME/go`, in my case `/home/mcarifio/go`. You can also install go using the more conventional `apt install golang`. It changes various file locations and it's an older version. But `go env GOPATH` should still default to `$HOME/go`. Yes, I know this is confusing as hell if you're not looking for it. Ubuntu is trying to innovate here and breaking eggs while making the omelette.

**Comment by chriswalz** [comment]
@mcarifio I haven't been able to replicate the issue but that one line with a single quote seems suspect. I made a small change that hopefully would do a better job of filtering out lines like that. Perhaps removing that line from the config would be worth it. 

```
alias.path !echo $PATH | tr ':' '
'
alias.br branch
```

**Comment by faizalpribadi** [comment]
Hi @chriswalz , 

`OSX Mojave`
`Iterm2`
`go version go1.15.2 darwin/amd64`

**Comment by reflog** [comment]
@chriswalz seems completion works in bash, but not in fish (I guess that was to be expected :) )

**Comment by alexmojaki** [comment]
Similar error to OP:

```
$ bit com......panic: runtime error: slice bounds out of range [:11] with length 7

goroutine 1 [running]:
github.com/posener/complete/v2.Complete(0x65d967, 0x3, 0x6d3ca0, 0xc0001af700)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/complete.go:83 +0x514
github.com/posener/complete/v2.(*Command).Complete(...)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/command.go:20
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/bitcomplete/complete.go:57 +0x75b
panic: runtime error: slice bounds out of range [:11] with length 7

goroutine 1 [running]:
github.com/posener/complete/v2.Complete(0x65d967, 0x3, 0x6d3ca0, 0xc00021f700)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/complete.go:83 +0x514
github.com/posener/complete/v2.(*Command).Complete(...)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/command.go:20
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/bitcomplete/complete.go:57 +0x75b
panic: runtime error: slice bounds out of range [:11] with length 7

goroutine 1 [running]:
github.com/posener/complete/v2.Complete(0x65d967, 0x3, 0x6d3ca0, 0xc0001e7740)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/complete.go:83 +0x514
github.com/posener/complete/v2.(*Command).Complete(...)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/command.go:20
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/bitcomplete/complete.go:57 +0x75b
```

`git config --get-regexp alias` displays nothing.

Using zsh with oh-my-zsh on Ubuntu 18.04.

In bash I just get:

```
$ bit comm<TAB>
commit         exit status 1  
```

No amount of further tabbing changes anything.

**Comment by ryanpcmcquen** [comment]
I think this is the same error ...
```
λ bit
exit status 1
runtime error: slice bounds out of range [-1:]
goroutine 1 [running]:
runtime/debug.Stack(0x12ae420, 0xc000100008, 0xc00013d750)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/chriswalz/bit/cmd.HandleExit()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/cmd/util.go:341 +0xc5
panic(0x1227e80, 0xc000150820)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/chriswalz/bit/cmd.BranchList(0x5d, 0x4f, 0x4f)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/cmd/util.go:179 +0x550
github.com/chriswalz/bit/cmd.BranchListSuggestions(0x13e26e0, 0xc00018e000, 0x5d)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/cmd/util.go:208 +0x34
github.com/chriswalz/bit/cmd.glob..func3(0x13e26e0, 0x1416ba0, 0x0, 0x0)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/cmd/rootShell.go:22 +0x8b
github.com/spf13/cobra.(*Command).execute(0x13e26e0, 0xc000108010, 0x0, 0x0, 0x13e26e0, 0xc000108010)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x13e26e0, 0x11d4565, 0xc00016c000, 0xc000174000)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/chriswalz/bit/cmd.Execute()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/cmd/rootShell.go:65 +0x31
main.bitcli(...)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/main.go:49
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/main.go:42 +0x171
```

**Comment by chriswalz** [comment]
I believe this issue is now resolved. Please update bit & bitcomplete. If you're still having issue (some of you may) please file another issue

**Comment by ryanpcmcquen** [comment]
@chriswalz, having trouble updating:
```
λ bash -c "curl -sf https://gobinaries.com/chriswalz/bit | sh; curl -sf https://gobinaries.com/chriswalz/bit/bitcomplete | sh && echo y | COMP_INSTALL=1 bitcomplete"

  ==> Downloading github.com/chriswalz/bit@master
  ==> Resolved version master to v0.5.1
  ==> Downloading binary for darwin amd64

  Error downloading, got 500 response from server


  ==> Downloading github.com/chriswalz/bit/bitcomplete@master
  ==> Resolved version master to v0.5.1
  ==> Downloading binary for darwin amd64

  Error downloading, got 500 response from server
```

**Comment by chriswalz** [comment]
Looks like gobinaries.com is down

**Comment by chriswalz** [comment]
Seems to be working now

**Comment by ryanpcmcquen** [comment]
0.5.2 works, thank you @chriswalz!

**Comment by switz** [comment]
Still seeing this on os x + fish shell + iterm:

```
$ bit panic: COMP_POINT env should be integer, got:

goroutine 1 [running]:
github.com/posener/complete/v2.Complete(0x1261aa7, 0x3, 0x12d7940, 0xc0002115c0)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/complete.go:79 +0x57f
github.com/posener/complete/v2.(*Command).Complete(...)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/command.go:20
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.8/bitcomplete/complete.go:57 +0x75b
```

version:

```
$ bit --version
bit version v0.5.6
git version 2.24.3 (Apple Git-128)
```

**Comment by howdoicomputer** [comment]
Also showing up here for fish shell / gnome terminal/ arch:

```
❯ bit panic: COMP_POINT env should be integer, got:                                                                                                                                                                                                            07:10:53

goroutine 1 [running]:
github.com/posener/complete/v2.Complete(0x660fe7, 0x3, 0x6d6820, 0xc0001b3500)
        /home/howdoicomputer/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/complete.go:79 +0x57f
github.com/posener/complete/v2.(*Command).Complete(...)
        /home/howdoicomputer/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/command.go:20
main.main()
        /home/howdoicomputer/go/pkg/mod/github.com/chriswalz/bit@v0.5.9/bitcomplete/complete.go:57 +0x75b

```

**Comment by pharrisee** [comment]
for the fish shell I had to set a universal exported envvar:

set -Ux COMP_POINT 1

After this bit completion no longer crashes and shows completions.

**Comment by mcarifio** [comment]
Working now:
```bash
bit --version
bit version v0.6.6
git version 2.25.1
```
An alias with "\n" will indeed cause problems.
