### ISSUE TITLE
Bit requires a minimum Git version

### ISSUE THREAD

**Issue by undefined-moe** [chriswalz/bit#41]
using the given install script(with curl)
ubuntu1604

![image](https://user-images.githubusercontent.com/29992205/95872606-8e1b9480-0da1-11eb-9e53-4ad4b7d0ee02.png)

**Comment by chriswalz** [comment]
@undefined-moe can you send me the output of this command (ideally with whatever files were staged etc.)

`git status --porcelain=v2`

**Comment by bbbbbr** [comment]
I'm seeing this as well. Just tried to install and run it for the first time.
Is there a minimum version of git required?
```
$ git status --porcelain=v2
error: option `porcelain' takes no value
usage: git status [<options>] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns

$ git status --porcelain
$ git status
On branch main
Your branch is up-to-date with 'origin/main'.
nothing to commit, working directory clean
$ git --version
git version 2.7.4
$ bit
runtime error: index out of range [-1]
goroutine 1 [running]:
runtime/debug.Stack(0x6a9840, 0xc0000a6008, 0xc0000c9670)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/chriswalz/bit/cmd.HandleExit()
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/cmd/util.go:359 +0xc5
panic(0x625300, 0xc0000167c0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/chriswalz/bit/cmd.FileChangesList(0x7fc8ea0bc108, 0x4031c5, 0x63b7ec)
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/cmd/util.go:253 +0x62d
github.com/chriswalz/bit/cmd.GitAddSuggestions(0x605ac0, 0xc000068450, 0x63b7ec)
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/cmd/util.go:265 +0x34
github.com/chriswalz/bit/cmd.CreateSuggestionMap(0x7d9740, 0xc0000c9c80, 0x56fd37)
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/cmd/rootShell.go:62 +0x3d6
github.com/chriswalz/bit/cmd.glob..func3(0x7d9740, 0x80ddc8, 0x0, 0x0)
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/cmd/rootShell.go:19 +0x45
github.com/spf13/cobra.(*Command).execute(0x7d9740, 0xc0000821b0, 0x0, 0x0, 0x7d9740, 0xc0000821b0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x7d9740, 0x5d2ae5, 0xc0000f4000, 0xc00001c600)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/chriswalz/bit/cmd.Execute()
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/cmd/rootShell.go:77 +0x31
main.bitcli(...)
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/main.go:55
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.5.12/main.go:43 +0x18b

```

**Comment by chriswalz** [comment]
@bbbbbr AH, yes looks like v2 isn't supported on your version so there appears to be an unintended minimum git version. 

If it's okay with you, can you upgrade and let me know if it works?

**Comment by undefined-moe** [comment]
```
喵? git status --porcelain=v2
error: option `porcelain' takes no value
usage: git status [<options>] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns

喵? git --version
git version 2.7.4
```

this version is provided by apt.
hoping to support.

**Comment by chriswalz** [comment]
should be fixed with 1d4011a4677c4836f4114c6f26f491bb81d25fa5

**Comment by chriswalz** [comment]
Please install again and lmk if it works

**Comment by bbbbbr** [comment]
When used with a newer version of git the issue no longer manifests (2.7.4 -> 2.17.1). 

However, I did the upgrade by way of a much belated OS upgrade (this was the a good prompt to finally do it. haha, a rather complicated way to get a new version of git i guess), so I can't be entirely certain that some other changes didn't contribute to resolving the issue. But most likely it was the newer version of git.

**Comment by undefined-moe** [comment]
git v2.7.4 now works. thanks
